[package]
name = "trading-risk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
trading-domain = { path = "../domain" }
uuid.workspace = true

[lints]
workspace = true
