[package]
name = "trading-webull-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
rumqttc.workspace = true
secrecy.workspace = true
tonic.workspace = true
trading-domain = { path = "../domain" }

[lints]
workspace = true
